/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ModsIndexRouteImport } from './routes/mods.index'
import { Route as InstancesIndexRouteImport } from './routes/instances.index'
import { Route as ModpackImportRouteImport } from './routes/modpack.import'
import { Route as InstancesIdRouteImport } from './routes/instances.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsIndexRoute = ModsIndexRouteImport.update({
  id: '/mods/',
  path: '/mods/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesIndexRoute = InstancesIndexRouteImport.update({
  id: '/instances/',
  path: '/instances/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModpackImportRoute = ModpackImportRouteImport.update({
  id: '/modpack/import',
  path: '/modpack/import',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesIdRoute = InstancesIdRouteImport.update({
  id: '/instances/$id',
  path: '/instances/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/instances/$id': typeof InstancesIdRoute
  '/modpack/import': typeof ModpackImportRoute
  '/instances/': typeof InstancesIndexRoute
  '/mods/': typeof ModsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/instances/$id': typeof InstancesIdRoute
  '/modpack/import': typeof ModpackImportRoute
  '/instances': typeof InstancesIndexRoute
  '/mods': typeof ModsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/instances/$id': typeof InstancesIdRoute
  '/modpack/import': typeof ModpackImportRoute
  '/instances/': typeof InstancesIndexRoute
  '/mods/': typeof ModsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/instances/$id'
    | '/modpack/import'
    | '/instances/'
    | '/mods/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/instances/$id'
    | '/modpack/import'
    | '/instances'
    | '/mods'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/instances/$id'
    | '/modpack/import'
    | '/instances/'
    | '/mods/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  InstancesIdRoute: typeof InstancesIdRoute
  ModpackImportRoute: typeof ModpackImportRoute
  InstancesIndexRoute: typeof InstancesIndexRoute
  ModsIndexRoute: typeof ModsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods/': {
      id: '/mods/'
      path: '/mods'
      fullPath: '/mods/'
      preLoaderRoute: typeof ModsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/': {
      id: '/instances/'
      path: '/instances'
      fullPath: '/instances/'
      preLoaderRoute: typeof InstancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modpack/import': {
      id: '/modpack/import'
      path: '/modpack/import'
      fullPath: '/modpack/import'
      preLoaderRoute: typeof ModpackImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/$id': {
      id: '/instances/$id'
      path: '/instances/$id'
      fullPath: '/instances/$id'
      preLoaderRoute: typeof InstancesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  InstancesIdRoute: InstancesIdRoute,
  ModpackImportRoute: ModpackImportRoute,
  InstancesIndexRoute: InstancesIndexRoute,
  ModsIndexRoute: ModsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
